services:
  diary:
    image: ${DOCKER_REGISTRY-}diary
    build:
      context: .
      dockerfile: Diary/Dockerfile
  db:
    container_name: container_db_postgresql
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: diarydb
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d diarydb -c 'SELECT 1' || exit 1"]
    volumes:
      - db_data:/var/lib/postgresql/data 
volumes:
  db_data:
