services: 
  
  #RoomDesigner Api
  roomsdesigner.api:
    image: ghcr.io/aaterekhov/roomsdesigner:latest
    container_name: roomsdesigner-service
    environment:
      "ASPNETCORE_URLS": "http://+:5100"
      ConnectionStrings:Postgres: "Host=roomsdesigner_db;Port=5432;Database=room;UserId=postgres;Password=admin24"
      RmqSettings:Host: "rabbit"
      RmqSettings:VHost: "/"
      RmqSettings:Login: "guest"
      RmqSettings:Password: "guest"
    depends_on:
      - roomsdesigner_db
    ports:
      - "5200:5100"

  #RoomDesigner Db
  roomsdesigner_db:
    image: postgres
    container_name: roomsdesigner_db
    restart: always
    environment:    
      POSTGRES_DB: room
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin24
    ports:
      - 5434:5432
    volumes:
      - 'roomsdesigner_data:/var/lib/postgresql/data'

  #Bookofhabits Api
  bookofhabits:
    image: ghcr.io/aaterekhov/bookofhabits:latest
    environment:
      "ASPNETCORE_URLS": "http://+:5100"
      ConnectionStrings:Postgres: "Host=habit_db;Port=5432;Database=Habit;UserId=postgres;Password=admin24"      
      RmqSettings:Host: "rabbit"
      RmqSettings:VHost: "/"
      RmqSettings:Login: "guest"
      RmqSettings:Password: "guest"
    container_name: habitsbook-service
    depends_on:
      - habit_db
    ports:
      - "5101:5100"

  #Bookofhabits Db
  habit_db:
    image: postgres
    container_name: habit_db
    restart: always
    environment:    
      POSTGRES_DB: Habit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin24
    ports:
      - 5455:5432
    volumes:
      - 'habitsbook_data:/var/lib/postgresql/data'

  #Broadcaster Api
  habits-broadcaster-api:
    image: ghcr.io/aaterekhov/broadcaster:latest
    container_name: 'habits-broadcaster-api'
    restart: always 
    ports:
      - "5010:5010"
    depends_on:
      - broadcaster-mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5010
      MongoSettings:Connection: "mongodb://root:example@broadcaster-mongodb:27017/broadcasterDb?authSource=admin"
      MongoSettings:DatabaseName: "broadcasterDb"      
      RmqSettings:Host: "rabbit"
      RmqSettings:VHost: "/"
      RmqSettings:Login: "guest"
      RmqSettings:Password: "guest"

  #Broadcaster Db
  broadcaster-mongodb:
    image: "mongo:latest"
    container_name: 'broadcaster-mongodb'
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbit:
    image: rabbitmq:3-management
    container_name: 'rabbit'
    restart: always
    hostname: rabbitmqhost    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    
     # Magazine Api
  magazine_api:
    image: ghcr.io/aaterekhov/magazine:latest
    container_name: magazineService
    depends_on:
      - redis
      - magazinepostgresdb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5300
      ConnectionStrings:Redis: redis:6379,ssl=False,abortConnect=False
      magazine_connection_db_string: "Host=magazinePostgresdb;Port=5432;Database=magazinedb;Username=postgres;Password=1234;Include Error Detail=true"
      RmqSettings:Host: "rabbit"
      RmqSettings:VHost: "/"
      RmqSettings:Login: "guest"
      RmqSettings:Password: "guest"
    ports:
      - 5400:5300

  # Magazine Db
  magazinepostgresdb:
    container_name: magazinepostgresdb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: magazinedb
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d magazinedb -c 'SELECT 1' || exit 1"]
    volumes:
      - magazine_data:/var/lib/postgresql/data

  # Diary Api
  diary_api:
    image: ghcr.io/aaterekhov/diary:latest
    container_name: diaryService
    depends_on:
      - redis
      - diarypostgresdb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5500
      ConnectionStrings:Redis: redis:6379,ssl=False,abortConnect=False
      diary_connection_db_string: "Host=diarypostgresdb;Port=5432;Database=diarydb;Username=postgres;Password=1234;Include Error Detail=true"
      RmqSettings:Host: "rabbit"
      RmqSettings:VHost: "/"
      RmqSettings:Login: "guest"
      RmqSettings:Password: "guest"
    ports:
      - "5600:5500"

  # Diary Db
  diarypostgresdb:
    container_name: diarypostgresdb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: diarydb
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d diarydb -c 'SELECT 1' || exit 1"]
    volumes:
      - diary_data:/var/lib/postgresql/data

  # Redis
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      
  #SantaBags Api
  santasbaghost:
    image: ghcr.io/aaterekhov/santasbag:latest
    environment:
      ASPNETCORE_URLS: http://+:5700
      SANTASBAG_DBCONTEXT_CONNECTION_STRING: "Host=santasbag_db;Port=5432;Database=santasbagdb;UserId=postgres;Password=postgres"        
    container_name: santasbaghost
    depends_on:
      - santasbag_db
    ports:
      - "5800:5700"
      
  #SantaBags Db
  santasbag_db:
    container_name: santasbag_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: santasbagdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - santasbag-data:/var/lib/postgresql/data
      
volumes:
  rabbitmq_data:
  roomsdesigner_data:
  postgres-data:
  habitsbook_data:
  mongo_data:
  magazine_data:
  diary_data:
  magazine_diary_rabbit_data:
  santasbag-data: