services:
  roomsdesigner.api:
    image: ${DOCKER_REGISTRY-}roomsdesignerapi
    build:
      context: .
      dockerfile: RoomsDesigner/Dockerfile      
    container_name: roomsdesigner-service
    environment:
      "ASPNETCORE_URLS": "http://+:5100"
      ConnectionStrings:Postgres: "Host=roomsdesigner_db;Port=5432;Database=room;UserId=postgres;Password=admin24"
    depends_on:
      - roomsdesigner_db
    ports:
      - "5200:5100"

  roomsdesigner_db:
    image: postgres
    container_name: roomsdesigner_db
    restart: always
    environment:    
      POSTGRES_DB: room
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin24
    volumes:
      - 'roomsdesigner_data:/var/lib/postgresql/data'
volumes:
  roomsdesigner_data:
